name: Label Commenter

on:
  workflow_call:

#on:
#  issues:
#    types: [labeled, unlabeled]
#  pull_request_target:
#    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Label Commenter
        #uses: peaceiris/actions-label-commenter@v1
        uses: peaceiris/actions-label-commenter@c2d00660c86f2b9ed0fb35b372c451558eba85b3
        with:
          config_file: krakendio/.github/.github/label-commenter-config.yml@main
