name: 'Close stale issues and PRs'
on:
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is marked as stale because it has been open over 90 days with no activity. Remove the stale label or comment or this will be closed in 15 days.'
          stale-pr-message: 'This PR is stale because it has been open over 90 days with no activity. Remove stale label or comment or this will be closed in 15 days.'
          close-issue-message: 'This issue was closed because it has been marked as stalled for 15 days with no activity.'
          close-pr-message: 'This PR was closed because it has been marked as stalled for 15 days with no activity.'
          days-before-issue-stale: 90
          days-before-pr-stale: 90
          days-before-issue-close: 15
          days-before-pr-close: 15
          operations-per-run: 200
          exempt-issue-labels: work in progress,roadmap
          exempt-pr-labels: work in progress,roadmap
          stale-pr-label: "stale"