name: Update Organization Profile

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
        working-directory: ./profile
      - run: |
          if [[ "${{ github.repository }}" != "krakend/.github" ]]; then
            echo "This workflow can only be executed on '.github' repository."
            exit 1
          fi
      - run: npm run update-readme
        working-directory: ./profile

      - id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          sign-commits: true
          commit-message: "[bot] Update README with latest info"
          branch: update-readme-${{ github.run_id }}
          title: "[bot] Update README with latest info"
          body: |
            This automated PR updates the README with the latest organization profile.
          reviewers: obokaman-com,alombarte

      - if: steps.pr.outputs.pull-request-url != ''
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "The organization README has been automatically updated with the latest blog articles: ${{ steps.pr.outputs.pull-request-url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "The org README was auto-updated with the latest blog articles. See PR: ${{ steps.pr.outputs.pull-request-url }}"
